import type { Metadata } from "next";
import Navbar from "@/components/shared/navbar/navbar";
import "../globals.css";



export const metadata: Metadata = {
  title: "Heaven Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <main className="flex flex-col items-center justify-between">
          <Navbar />
          <section className="relative min-h-screen w-full">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
